# Generated by Django 3.2 on 2022-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_advert_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='approved',
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
