# Generated by Django 3.2 on 2022-04-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220324_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='firearm_make',
            new_name='item_make',
        ),
        migrations.RenameField(
            model_name='advert',
            old_name='firearm_model',
            new_name='item_model',
        ),
        migrations.AlterField(
            model_name='advert',
            name='calibre',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
