# Generated by Django 3.2 on 2022-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220403_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('1', 'Firearm'), ('2', 'Optic'), ('3', 'Accessory')], default='Firearm', max_length=20),
        ),
    ]
