# Generated by Django 3.2 on 2022-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_advert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type',
            field=models.CharField(choices=[('firearm', 'Firearm'), ('optic', 'Optic'), ('accessory', 'Accessory')], default='Firearm', max_length=20),
        ),
    ]
