# Generated by Django 3.2 on 2022-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220406_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message_body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='sender_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='advert',
        ),
    ]
