# Generated by Django 3.2 on 2022-04-09 17:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220409_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
