# Generated by Django 3.2 on 2022-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_advert_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='contact_details',
            field=models.CharField(default='Eg. Your email or phone no.', max_length=100),
        ),
    ]
