# Generated by Django 3.2 on 2022-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_advert_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='contact_details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
