# Generated by Django 3.2 on 2022-04-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_advert_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='status',
        ),
    ]
