# Generated by Django 3.2 on 2022-04-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_advert_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
